### ISSUE TITLE
Can't add account

### ISSUE THREAD

**Issue by davecowen** [minego/phnx#143]
When I load up Project Macaw 1.5.7 in WebOS 2.1.2 on my Veer and click on the "Add New Account" button, I get a blank screen with a refresh button in the lower right hand corner. After that point, the app does not function. It looks like other forum members have had this issue as well on a Pre 3. Is 2.1.2 still supported?

Thanks!

**Comment by minego** [comment]
Check the clock on your device. If the clock is wrong you will get a 
white page. This is a known issue.

**Comment by davecowen** [comment]
That was it. I was in Airplane mode, so the time was close but not accurate. Thanks so much for the quick response.

**Comment by minego** [comment]
On 04/30/15 09:13, davecowen wrote:
> That was it. I was in Airplane mode, so the time was close but not
> accurate. Thanks so much for the quick response.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/minego/phnx/issues/143#issuecomment-97833212>.
>
np, glad to help :)

Twitter tends to be very picky about the time for adding an account. I'd 
like to show a proper error there eventually.
